USE [master]
GO

IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = N'MvcExercise')
BEGIN
CREATE DATABASE [MvcExercise]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MvcExercise', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLDEV\MSSQL\DATA\MvcExercise.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MvcExercise_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLDEV\MSSQL\DATA\MvcExercise_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
END
GO
ALTER DATABASE [MvcExercise] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MvcExercise].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [MvcExercise] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [MvcExercise] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [MvcExercise] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [MvcExercise] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [MvcExercise] SET ARITHABORT OFF 
GO
ALTER DATABASE [MvcExercise] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [MvcExercise] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [MvcExercise] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [MvcExercise] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [MvcExercise] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [MvcExercise] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [MvcExercise] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [MvcExercise] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [MvcExercise] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [MvcExercise] SET  DISABLE_BROKER 
GO
ALTER DATABASE [MvcExercise] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [MvcExercise] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [MvcExercise] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [MvcExercise] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [MvcExercise] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [MvcExercise] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [MvcExercise] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [MvcExercise] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [MvcExercise] SET  MULTI_USER 
GO
ALTER DATABASE [MvcExercise] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [MvcExercise] SET DB_CHAINING OFF 
GO
ALTER DATABASE [MvcExercise] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [MvcExercise] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [MvcExercise] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'MvcExercise', N'ON'
GO
ALTER DATABASE [MvcExercise] SET QUERY_STORE = OFF
GO
USE [MvcExercise]
GO
GRANT VIEW ANY COLUMN ENCRYPTION KEY DEFINITION TO [public] AS [dbo]
GO
GRANT VIEW ANY COLUMN MASTER KEY DEFINITION TO [public] AS [dbo]
GO

USE [master]
GO
ALTER DATABASE [MvcExercise] SET  READ_WRITE 
GO
